#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/cluster_init
- name: Run command with arguments 
  ansible.builtin.command:
    cmd: "kubeadm init --apiserver-advertise-address='{{ node_IP }}'   --upload-certs "
  args:
    creates: /etc/kubernetes/admin.conf
