#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/cluster_join
- name: Run kubeadm token create and capture output
  ansible.builtin.command: " kubeadm token create --print-join-command"
  register: command_result  # Saves ALL output here    
  when: inventory_hostname in groups['master-node']  # Only run on master nodes

- name: Join cluster directly (No file needed)
  ansible.builtin.command: "{{ hostvars[groups['master-node'][0]]['command_result']['stdout'] }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: inventory_hostname in groups['worker-nodes'] 

