#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/swap_manage
    - name: Turn off all active swap
      command: swapoff -a
      become: yes
      ignore_errors: yes  # In case no swap exists

    - name: Create ansible_swap_OFF  file
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/ansible_swap_OFF
        state: touch          

    - name: Remove ALL swap entries from fstab 
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^.*(swap|SWAP).*$'
        replace: '# Ansible: Removed here\n'
        backup: yes
