#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/common
- name: Example from an Ansible Playbook
  ansible.builtin.ping:
- name: Install pip (if missing)
  apt:
    name: python3-pip
    state: present

- name: Install kubernetes package
  pip:
    name: kubernetes
    executable: pip3
    
- name: Append local file content to remote file (idempotent)
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: "{{ lookup('file', 'cluster_nodes_hosts') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - APPENDED CONTENT"
    insertafter: EOF


